In [27]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [28]:
dataset = pd.read_csv('Test_Data.csv')
X = dataset.iloc[:, 2:-1].values
y = dataset.iloc[:, -1].values

In [29]:
print(X)

[['Lavasa' 'Weekend' 'Summer' 0 0 24]
 ['Lavasa' 'Weekend' 'Summer' 0 0 25]
 ['Lavasa' 'Weekend' 'Summer' 0 0 25]
 ...
 ['Casa Bliss Goa 23 bhk' 'Weekend' 'Summer' 0 0 23]
 ['Casa Bliss Goa 23 bhk' 'Weekend' 'Summer' 0 0 24]
 ['Casa Bliss Goa 23 bhk' 'Weekend' 'Summer' 0 0 26]]


In [30]:
print(y)

[ 3671.  4381.  4381. ... 54000. 60000. 46000.]


In [31]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(sparse=False), [0,1,2])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

print(X)

[[0.0 0.0 0.0 ... 0 0 24]
 [0.0 0.0 0.0 ... 0 0 25]
 [0.0 0.0 0.0 ... 0 0 25]
 ...
 [0.0 0.0 0.0 ... 0 0 23]
 [0.0 0.0 0.0 ... 0 0 24]
 [0.0 0.0 0.0 ... 0 0 26]]


C:\Users\Atharav Jadhav\AppData\Roaming\Python\Python311\site-packages\sklearn\preprocessing\_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


In [32]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 6)

In [33]:
y_train = y_train.reshape(-1, 1)

In [34]:
X_train = X_train.astype('float32')
y_train = y_train.astype('float32')

In [35]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [36]:
ann = tf.keras.models.Sequential()
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))
ann.add(tf.keras.layers.Dense(units=10, activation='relu'))
ann.add(tf.keras.layers.Dense(units=8, activation='relu'))
ann.add(tf.keras.layers.Dense(units=1))

In [37]:
ann.compile(optimizer = 'adam', loss = 'mean_squared_error')

In [38]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 1000)

Epoch 1/1000


88/88 [==============================] - 1s 873us/step - loss: 521391904.0000
Epoch 2/1000
88/88 [==============================] - 0s 850us/step - loss: 521193632.0000
Epoch 3/1000
88/88 [==============================] - 0s 922us/step - loss: 520368128.0000
Epoch 4/1000
88/88 [==============================] - 0s 816us/step - loss: 517566176.0000
Epoch 5/1000
88/88 [==============================] - 0s 809us/step - loss: 510080384.0000
Epoch 6/1000
88/88 [==============================] - 0s 903us/step - loss: 494196960.0000
Epoch 7/1000
88/88 [==============================] - 0s 893us/step - loss: 466649408.0000
Epoch 8/1000
88/88 [==============================] - 0s 1ms/step - loss: 425840320.0000
Epoch 9/1000
88/88 [==============================] - 0s 939us/step - loss: 372959872.0000
Epoch 10/1000
88/88 [==============================] - 0s 864us/step - loss: 312903584.0000
Epoch 11/1000
88/88 [==============================] - 0s 923us/step - loss: 253996752.0000
Epoch 12/100

In [39]:
y_pred = ann.predict(X_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

22/22 [==============================] - 0s 810us/step
[[16085.1  10000.  ]
 [ 6240.73  4500.  ]
 [ 6654.04  4000.  ]
 ...
 [ 8024.85 13080.  ]
 [17791.78  7281.94]
 [ 7364.49  5000.  ]]


In [40]:
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
mse = mean_squared_error(y_test, y_pred)
mae = mean_absolute_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print("Mean Squared Error:", mse)
print("Mean Absolute Error:", mae)
print("R2 Score:", r2)

Mean Squared Error: 158653585.4354157
Mean Absolute Error: 7390.019416107438
R2 Score: 0.4421340738534242
